### PR TITLE
Milestone: Deploy website on GitHub pages

### PR DESCRIPTION
**Pull request by Timbar09**
- Deployed site on GitHub pages on this branch. On the main branch, it is deployed on Neltyfy.
- Updated README.md file
- Updated intro section animations
- Updated projects section and contact-form transitions

### CODE REVIEW

**Review by Olamarx — CHANGES_REQUESTED** [review]
Hi @Timbar09,

Good job so far, indeed you have spent time on this project!
There are some issues that you still need to work on to go to the next project but you are almost there!


## Highlights
- Git and GitHub flow ✔️

## Required Changes ♻️
_Check the comments under the review._
- [ ] Kindly make use of GitHub pages as required. As a developer, it is encouraging and professional to stick to project requirements. You can find how to deploy it [here](https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site)

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Timbar09** [comment]
@Olamarx  I have deployed the site on the Github pages. If you look at the updated README.md file the branch that I am trying to merge.

Previously, I deployed it on Netlify. Now it is on GitHub pages.

**Review by levy002 — APPROVED** [review]
## Hello @Timbar09 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



## Status: APPROVED :fire:  :fire: 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Timbar09** [comment]
Thanks, @levy002

**Pull request merged**
