### PR TITLE
Milestone: Add accessibility to page

### PR DESCRIPTION
**Pull request by Timbar09**
- Page titles - no issues found
- Image text alternative  - updated the image text alternative to a more descriptive text
- Text headings - no issues found
- Color contrast - no issues found
- Resize - no issues found
- Interaction - added focus-within effects to section cards
- Moving content - no issues found
- Multimedia - no issues found
- The basic structure of the page - no issues found

### CODE REVIEW

**Review by levy002 — APPROVED** [review]
## Hello @Timbar09  & @yaredtekle022 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 🎉  🎉  🎉 



## Status: APPROVED :fire:  :fire: 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Timbar09** [comment]
Thank you for approving our review @levy002 

However, I think you made a mistake by mentioning @dhirajsingha143 in this particular review instead of @yaredtekle022 who was the actual collaborator on this PR.

**Comment by levy002** [comment]
Thank you @Timbar09 for mentioning that!

**Comment by Timbar09** [comment]
No problem @levy002 . Thanks for following up.

**Pull request merged**
